### ISSUE TITLE
不正な一括変名を行った際にcfilerがハングアップする

### ISSUE THREAD

**Issue by geotrader** [crftwr/cfiler#1]
### Issue type
- Bug report

### Versions
- cfiler
    - 2.46
- OS
    - Windows 10 64bit Pro

### Description:
1. 複数のファイルに対して一括変名を行う際に正規表現をONにします．
1. 正規表現に.*を指定して全てとマッチングさせ置換内容に\1をセットします
1. 実行するとno such groupとなり,変名の確認ウィンドウが閉じれなくなり操作不能となる

### Expected behavior
エラーメッセージが表示されるかなどし,Escで元の状態に戻れること

### note
対象を()でくくっていないにもかかわらず\1を指定するミスを起こしたイレギュラーなケースです.
画像は古いままですが2.46でも再現したため,バージョンと再現環境を更新しました.

![2016y03m14d_213328093](https://cloud.githubusercontent.com/assets/15902749/13744718/f7c65598-ea2c-11e5-9770-47f14eb7f365.jpg)
![2016y03m14d_213336377](https://cloud.githubusercontent.com/assets/15902749/13744719/f7e6a820-ea2c-11e5-8ec5-8d6ba3cf4c4c.jpg)

**Comment by crftwr** [comment]
2.47で修正します
