### ISSUE TITLE
画像閲覧中の不具合レポート

### ISSUE THREAD

**Issue by geotrader** [crftwr/cfiler#2]
画像が100枚ほど入ったディレクトリで

ENTERで画像を閲覧→5回スペース→Esc→画像を削除をループする
再現率：2/10回
Escを押下した時にカーソル位置が最初のエンターを押して画像を閲覧した時から,カーソル位置が動いておらず選択出来ていない現象が起きることがあります.

**Comment by crftwr** [comment]
次のバージョンで修正
