### ISSUE TITLE
シンボリックリンクディレクトリを削除すると中身のファイルも同時に消える

### ISSUE THREAD

**Issue by geotrader** [crftwr/cfiler#4]
### Issue type
- Bug report

### Versions
- cfiler
    - 2.45
- OS
    - Windows 10 64bit Pro

### Description:
1. MKLINK /D <リンク> <ターゲット>でファイルを含むディレクトリのシンボリックリンクを作成する
1. cfilerでリンクを作ったディレクトリに移動
1. シンボリックリンクを選択して削除する
1. シンボリックリンクの元のディレクトリを覗くと中身が消えている

### Expected behavior
シンボリックリンク自体のみ削除され、中身のファイルは削除されない

**Comment by crftwr** [comment]
問題のレポートをありがとうございます。
修正します。
修正版が出るまでの間、設定で削除にゴミ箱を使うように変更するなどの方法でご対処ください。

**Comment by crftwr** [comment]
次の ver 2.46 で修正されます。
