### ISSUE TITLE
ファイルの削除時にエラーが出て削除できない

### ISSUE THREAD

**Issue by wildlarva** [crftwr/cfiler#42]
### 現象
ファイルの削除時に以下のエラーが出てファイルが削除できない。
```
ごみ箱に投棄 :
  ファイル : C:/Users/wildlarva/Downloads\Q631YSTR001201901070923141.pdf
Traceback (most recent call last):
  File "../ckit\ckit_threadutil.py", line 231, in run
  File ".\cfiler_mainwindow.py", line 3307, in jobDelete
  File "../ckit\ckit_misc.py", line 410, in deleteFilesUsingRecycleBin
ValueError: embedded null character
Done.
```

### 本現象の再現方法
1. 内骨格を起動する。
1. スペースキーを押下し、いずれかのファイルを１つ選択する。
1. Kキーを押下し、ファイルを削除する。
1. "ゴミ箱への投棄の確認"ダイアログにおいてエンターキーを押下し、"はい"を選択する。

### 本現象の発生した環境
* 内骨格:  version 2.48
* Windows:  10 Pro 1809
* 内骨格の設定
  * 削除動作選択: デフォルトでOSのごみ箱を使用する

### 参考：考えられる原因(未検証)
以下の箇所において`ctypes.c_wchar_p`に`"\0"`の文字列を設定している。
ckit_misc.py
```python
def deleteFilesUsingRecycleBin( hwnd, filename_list ):
    ...
    joint_filenames = ""
    for filename in filename_list:
        filename = filename.replace("/","\\")
        joint_filenames += filename
        joint_filenames += '\0'
    joint_filenames += '\0'
    ...
    fileopdata.pFrom = joint_filenames
    ...
```

pythonの以下のバグにより本箇所がエラーとなっている可能性がある。
https://bugs.python.org/issue32745

**Comment by crftwr** [comment]
レポートをありがとうございます。
問題の再現を確認しました。調査、修正します。

**Comment by crftwr** [comment]
下のように修正予定

c_joint_filenames = ctypes.create_unicode_buffer(joint_filenames)
fileopdata.pFrom = ctypes.cast( ctypes.byref(c_joint_filenames), ctypes.c_wchar_p )

**Comment by crftwr** [comment]
v 2.49 で修正

**Comment by hironei** [comment]
v2.50に更新したところ、本現象が発生するようになりました。
v2.49では問題なかったのですが、ご確認いただけますでしょうか。
※ゴミ箱を使わない削除については正常動作します。

```
ごみ箱に投棄 :
  ファイル : c:\work\tmp\xxxx.log
Traceback (most recent call last):
  File "../ckit\ckit_threadutil.py", line 231, in run
  File ".\cfiler_mainwindow.py", line 3340, in jobDelete
  File "../ckit\ckit_misc.py", line 410, in deleteFilesUsingRecycleBin
ValueError: embedded null character
```

**Comment by crftwr** [comment]
問題が再発していました。ver 2.51 で再度修正しました。
早速のレポートをありがとうございました。
