### ISSUE TITLE
config.pyにてMキーの再割り当てをすると、期待した動作にならない

### ISSUE THREAD

**Issue by reppets** [crftwr/cfiler#5]
### 環境

* ver. 2.45
* Windows 10 64bit

### 事象

config.py にてMキーの再割り当てをしようとして、以下のような設定をしましたが、再読み込み後、Mキーをおしても以下の例の場合のジャンプリストは表示されず、Mkdirが起動します。
(ファイル選択状態の場合は、Moveではなくジャンプリストが表示されました)。
```python
# config.py
def configure(window):
    window.keymap["M"]=window.command_JumpList
```

また、Mはkeymapに文字列ではなく`ckit.KeyEvent`オブジェクトをキーとしているためかと思い、以下を追加してみましたが、エラーとなりました。

```python
# config.py
import ckit

def configure(window):
    del window.keymap[ckit.KeyEvent(ord('M'),0,extra=0)]
    del window.keymap[ckit.KeyEvent(ord('M'),0,extra=1)]
    window.keymap["M"]=window.command_JumpList
```

以下エラー内容
```
ERROR : 設定ファイルの実行中にエラーが発生しました.
Traceback (most recent call last):
  File "../ckit\ckit_userconfig.py", line 42, in callConfigFunc
  File "config.py", line 65, in configure
  File "../ckit\ckit_key.py", line 439, in \_\_delitem\_\_
  File "../ckit\ckit_key.py", line 338, in fromString
AttributeError: 'KeyEvent' object has no attribute 'upper'
```

### 期待される動作
文字列`"M"`によるキーの再割り当てで、指定したファンクションが呼ばれる。

**Comment by reppets** [comment]
ワークアラウンドを http://reppets.net/blog/2017-05-01-naikokkaku.html で公開しておりますので、ユーザーの方で同じ問題に合っている方はご参考ください。

**Comment by crftwr** [comment]
レポートをありがとうございます。
ご指摘のとおり、Keymapの del / get に文字列が渡ってくることを前提としている箇所がありました。
修正いたします。

**Comment by crftwr** [comment]
ver 2.46 で修正しました。
