### ISSUE TITLE
ビューワーのヘルプでエラー

### ISSUE THREAD

**Issue by SinisterSoftware** [crftwr/cfiler#54]
テキストビューワーや画像ビューワーで[F1]キーでヘルプを表示できない

Traceback (most recent call last):
  File ".\cfiler_diffviewer.py", line 289, in onKeyDown
TypeError: command_Help() takes 0 positional arguments but 1 was given

**Comment by SinisterSoftware** [comment]
_config.pyのTextViewerやImageViewerのcommand_helpの引数が設定されていない
def command_help(): -> def command_help(info):

**Comment by crftwr** [comment]
v2.61 で修正。config.py の修正が必要。
