### ISSUE TITLE
ごみ箱経由の削除ができない

### ISSUE THREAD

**Issue by hironei** [crftwr/cfiler#58]
ごみ箱経由の削除ができないようです。
特にエラーも出ていないためあまり情報がありませんが、環境と再現手順を報告させていただきます。

### 環境

* Windows 10 Pro 64bit
* 内骨格 v2.61

### 再現手順

* 削除対象ファイルを選択
* コマンドのDeleteを実行
* 「ごみ箱へ投棄しますか？」で「はい」を選択
* 以下メッセージがログペインに表示されるが、対象は削除されない（ファイル・ディレクトリに関わらず)
    ```
    ごみ箱に投棄 :
      ファイル : c:\xxxx
    Done.
    ```

**Comment by crftwr** [comment]
原因：ctypes の使い方が64bit に対応していない

**Comment by crftwr** [comment]
v2.62 で修正しました。
レポートをありがとうございました。

**Comment by hironei** [comment]
対応ありがとうございました。
正常動作することが確認できました。
