### ISSUE TITLE
migemoが有効にならない

### ISSUE THREAD

**Issue by novaoki** [crftwr/cfiler#9]
お世話になります。
久々に内骨格を触ってみようと思い、ver 2.46をダウンロードさせていただきました。
マニュアルの通りmigemo辞書の配置、I-Searchの切り替えを行いましたが思った挙動になりませんでした。
こちら何かさらに設定が必要なのでしょうか？
よろしくお願い致します。

**Comment by crftwr** [comment]
問題が再現しませんでした。どのような文字で検索しようとしているかをお知らせください。
次のバージョンで辞書の読み込みに失敗したとき、エラーメッセージを表示するようにします。

**Comment by novaoki** [comment]
@crftwr 文字列としては「無題.png」を「mudai」でサーチしようとすると「m」の次の「u」が入力されない状態でした。

**Comment by crftwr** [comment]
先頭を大文字にして、Mudai だったらどうでしょうか？
内骨格では、Migemo モードにしたうえで、大文字小文字混在の文字列で検索した場合のみ、Migemo検索を使い、それ以外の場合は、アルファベットのまま検索します。

**Comment by novaoki** [comment]
@crftwr ご指摘の方法で施行したところMigemoの挙動になりました。認識不足でお手数おかけいたしまして誠に申し訳ありませんでした。
ちなみになのですが、設定(.py)などでこの挙動を簡単に反転することは可能だったりするのでしょうか？(あふは小文字そのままでMigemoだったので…)
